### ISSUE TITLE
How to use the onLoad attribute

### ISSUE THREAD

**Issue by tomkiss** [brandonweiss/charge#1029]
To reduce render-blocking resources, I [defer CSS](https://web.dev/defer-non-critical-css/) loading using something like this in the document `<head>`:

```
<link rel="preload" href="/assets/css/styles.css" as="style" onLoad="this.onLoad=null;this.rel='stylesheet'" />
<noscript><link href="/assets/css/styles.css" as="style" rel="stylesheet" /></noscript>
```

Charge will strip out the `onLoad` attribute however. Just wondering - is there a way to ensure this gets built in the compiled HTML source?

Any help appreciated. Love Charge.js btw!

**Comment by brandonweiss** [comment]
Hey, thanks!

I think that although React removes the `onLoad` attribute from the DOM, I believe it does bind an event handler to that element.

I might take a look in your browser console and see if it’s throwing any errors, because I think it might be expecting a function, rather than a string. Something like:

```jsx
<link rel="preload" href="/assets/css/styles.css" as="style" onLoad={() => console.log('hey')} />
```

That said, are you definitely sure you want to do defer loading your stylesheet? There is a reason the `defer` attribute is available on the `script` element but not the `link` element. Stylesheets are render-blocking because loading an un-styled page usually isn’t that useful, can result in a flash of un-styled content, and causes layout jank. Google also recently made “Cumulative Layout Shift” a core web vital and might penalize you for the layout shift.

**Comment by tomkiss** [comment]
Thanks for your quick response.

This is a code snippet from another project which works in vanilla HTML land (the Google developers site references that one also). It also strips it out with the example you suggest also. I tried using a Fragment and dangerouslySetInnerHTML but that doesn't appear to work either. Seems like there's no way to achieve this then?

(You're right about page shift, this particular technique works well for secondary level stylesheets, alongside critical-css being injected into the HTML document).

**Comment by brandonweiss** [comment]
Nice, glad you got it working! I love React but sometimes you really have to jump through some hoops for things that should be simple 🙃
