### ISSUE TITLE
add a main website for the project

### ISSUE THREAD

**Issue by zakariaharti** [brandonweiss/charge#117]

**Comment by brandonweiss** [comment]
Hey! Thanks for your interest!

This issue is very timely 😂 I _do_ want to add a separate website for Charge’s documentation, but I also want to keep the documentation in the README because I think there is value in having it there. That would require updating the documentation in two places, though, which I don’t want to do. So to make this easier I started working on another open-source project that will automatically take the README and generate a nice documentation site from it that can then be hosted on pages. It’s not ready yet but I’ll update this issue here as soon as it is!

**Comment by brandonweiss** [comment]
This is done!

https://charge.js.org
