### ISSUE TITLE
Offline clients

### ISSUE THREAD

**Issue by TomFreudenberg** [brandonweiss/charge#812]
Hi - thanks for publishing Charge

I like the easyness of your concept but wonder how you manage offline states / apps when alny having SSR. Any ideas for that?

We currently work with Gatsby just to get this feature ob offline support from webpack.

Thanks for your feedback (when not surfin or thinking about surfin)
Tom

**Comment by brandonweiss** [comment]
Hey! I think there is a typo in “when alny having SSR” so I’m not sure what you mean… but generally my understanding is that “offline” support is really only useful for (complex) client-side applications, right? Charge is for building relatively simple static websites. They _can_ contain JavaScript but they certainly don’t have to.

Maybe a better way of explaining it is if that Charge and Gatsby are not different tools to do the same job—they do entirely different jobs. So if you’re using Gatsby to build an application then Charge would be an extremely poor replacement for it. However, if you’re using Gatsby to build a relatively simple static website then Charge could be a better tool, but in that case I can’t imagine you would need offline support.

Does that make sense? Let me know if I’ve misunderstood anything!

**Comment by TomFreudenberg** [comment]
Hey Brandon

thanks for your feedback.

The question is at least: what is a _complex_ website?

In our case we generate a very small PWA having only a main file, all navigation just inside the index page (tabs, dialogs, top to bottom)

But linked some assets like logo and icon images and a few small sized pdf documents.

Comsumers will save the App to their Homescreen and expect "full" function online and offline. That means, icons and images should be shown wether or not online AND the pdfs should are always available.

The App will check from time to time with it's worker if some update is online.

So - again - is that already a complex website?

Before Gatsby I used Jekyll in conjunction with materializecss. In that setup we also had no offline support and switched for Gatsby.

Does this make sense to you?

**Comment by brandonweiss** [comment]
Yeah, that’s fair, complexity can be very subjective. Let me put that aside and approach this from another angle.

I just did a small amount of research about how to make a website work offline and it seems like you register a service worker that caches all the pages/assets and then intercepts/manages requests in such a way that the website continues to function even when offline.

It seems like there’s no reason you shouldn’t be able to add offline support to a website built with Charge (or any website, really). Although you did mention that you couldn’t make an offline website with Jekyll—why is that?

**Comment by TomFreudenberg** [comment]
> Although you did mention that you couldn’t make an offline website with Jekyll—why is that?

I had not realized webpack or similar with Jekyll be myself but using Gatsby excatly for that - out of the box offline assets support

So when using charge - I would have to setup webpack or similar by myself

**Comment by brandonweiss** [comment]
In terms of offline support, I think using Charge would be a similar experience to using Jekyll (or most static site generators). All Charge does is generate static HTML and transpile assets. You can do anything you want beyond that (like create an offline website) but it’s up to you to do it—Charge doesn’t automatically do it for you.

Honestly it seems like Gatsby is the right tool for you. It does everything you already want… is there some reason you were thinking about switching from Gatsby to Charge?

**Comment by TomFreudenberg** [comment]
Hey Brandon

thanks for that kind of technical pro con discussion.

Gatsby does all the offline while has clever included webpack. But it does a lot more and on case that they are having their own cosmos in mind it is still growing and become a monster in case of tools to use and plugins and ...

We are currently have a build process prepared via AWS lambda and pipelines and the gatsby build environment is nearly max size big as allowed for lambdas. So a simple tool like Gatsby in the beginning would be a nice one ;-)

That's why looking for your Charge.

But at least you are right, all the "nice" from Gatsby had to be re-implemented when switching.

I have to think about it ... Maybe best to setup a small POC to check how all does fit or not.

Looking forward if you have some more good arguments and ideas.

Thanks
Tom

**Comment by brandonweiss** [comment]
Got it. There’s this great [post I read recently about complexity](https://ferd.ca/complexity-has-to-live-somewhere.html). The main idea is that complexity has to live _somewhere_.

In the case of Gatsby, the complexity lives inside the tool. If you’re making a complex website then Gatsby can be great. It might be a bit complicated to use, but ultimately you’ll be able to easily do complex things while keeping the code for your website (relatively) simple. But if you’re making a simple website then all that complexity mostly just gets in the way. That’s why I built Charge.

In the case of Charge, the complexity lives outside the tool. If you make a simple website then there is no complexity. The tool is simple and your website is simple. But if you need to do something complex, then that complexity has to live inside your website. Whether or not that makes sense depends on personal tastes and how complex a website someone is trying to build, but in general that why I say that Charge is only for simple websites.

So to bring it all back around to your original question, offline support in Charge is possible, but you’d have to handle it yourself. Unfortunately it wouldn’t make sense to add it to Charge because it’s not something that most people would want their websites to support.

**Comment by TomFreudenberg** [comment]
Thanks @brandonweiss for linking the article and your conclusion.
